### ISSUE TITLE
filename customize

### ISSUE THREAD

**Issue by kingzleshe** [PresidioCode/ConfigMerge#1]
Hi

I have looked through the code that filename = host + ".txt"
not quite understand the host parameter, it is not in the csv file.

what if I want to sort the txt file, let say 1.Site-A  2.Site-B  3.Site-C
"1." is a customized part, "Site-A" is the device hostname.
How can achieve the goal？
Any advice would be appreciated

**Comment by jamiecaesar** [comment]
The host variable in the Python script uses a for loop to pull all the
"HOSTNAME" variables from the CSV file.  The idea is that there will be a
file with the hostname of each device in the CSV file and that file will
contain the script for that particular device.   I'm not sure I'm following
what you are trying to do with the sorting, but hopefully that answers your
question.

**Comment by kingzleshe** [comment]
can I pull more than one variables from the CSV file？

**Comment by jamiecaesar** [comment]
The program will not do that as-is.  It was written for a very specific use-case that I had a need for 4 or 5 years ago.

Feel free to take the code and modify as you need to, but this isn't a tool I plan to keep developing -- mostly because there are already Python modules out there to do the bulk of this work that I wasn't aware of at the time (this was the first Python program I wrote).   If I needed to re-write this tool, I would use Jinja2 for all of the templating, and then I'd only have to write the code that imports the CSV and passes that data into Jinja2.

**Comment by kingzleshe** [comment]
Thanks, base on your code , I have solved it out.

**Comment by jamiecaesar** [comment]
Glad to hear it!  I'll go ahead and close this issue.
